language: generic

sudo: true

python:
  - "3.7"

addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"

before_install:
  - |
    echo 'Add neovim PPA.'
    sudo add-apt-repository ppa:neovim-ppa/unstable -y
  - sudo apt-get update  -q
  - |
    echo 'Install foreign language packs for international tests.'
    sudo apt-get install -y language-pack-de language-pack-es
  - |
    echo 'Install neovim.'
    sudo apt-get install -y neovim
    nvim --version
  - |
    echo 'Clone dependencies.'
    mkdir -p ~/.config/nvim
    git clone --depth=1  https://github.com/hardcoreplayers/ThinkVim ~/.config/nvim
  - cd ~/.config/nvim

install:
    - nvim -e -i NONE -N -u core/packman.vim -c "try | call dein#install() | finally | echomsg '' | qall! | endtry"

notifications:
  email: false
